version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: gradle test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  hello:
    jobs:
      - build
      - test:
          requires:
            - build

references:
  save_composer_cache: &save_composer_cache
    name: Save composer cache
    paths:
      - ./vendor
    key: v1-dependencies-composer-{{ checksum "composer.lock" }}

  restore_composer_cache: &restore_composer_cache
    name: Restore composer cache
    keys:
      - v1-dependencies-composer-{{ checksum "composer.lock" }}
      - v1-dependencies-composer-

  save_node_cache: &save_node_cache
    name: Save node modules cache
    paths:
      - ./node_modules
    key: v1-dependencies-node-{{ checksum "yarn.lock" }}

  restore_node_cache: &restore_node_cache
    name: Restore node modules cache
    keys:
      - v1-dependencies-node-{{ checksum "yarn.lock" }}
      - v1-dependencies-node

  working_directory: &working_directory ~/labrador
  